FROM ruby:2-slim as jekyll
RUN apt-get update && \
        apt-get install -y make libssl-dev g++ git libcurl4
WORKDIR /app

RUN gem install bundler:2.2.0

COPY ./Gemfile* ./
COPY ./vendor ./vendor
RUN bundle install
COPY ./ ./

CMD ["bundle", "exec", "jekyll", "serve", "-H", "0.0.0.0", "--livereload"]
