FROM ruby:2.7.5
WORKDIR /app

RUN gem install bundler:2.2.0

COPY ./Gemfile* ./
COPY ./vendor ./vendor
RUN bundle config set --local path '/gems'
RUN bundle install
COPY ./ ./

EXPOSE 4000
EXPOSE 35729

CMD ["bundle", "exec", "jekyll", "serve", "-H", "0.0.0.0",  "--livereload"]
