name: Build, Test and Publish

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t "${DOCKER_IMAGE}-dev" -f Dockerfile.dev .
    - name: Build Jekyll and test HTML
      run: docker run "${DOCKER_IMAGE}-dev" bundle exec rake test
  build_and_publish:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Production Image
        run: docker build -t ${DOCKER_IMAGE} .
      - name: Login to Docker Registry
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: "Push Image"
        run: docker push "$DOCKER_IMAGE":latest
 
