name: Build, Test and Publish

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t sterexx/stex.codes-dev -f Dockerfile.dev .
    - name: Build Jekyll and test HTML
      run: docker run sterexx/stex.codes-dev bundle exec rake test
